name: Jobs

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  deploy-ingest-job:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

    permissions:
      contents: read
      id-token: write  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth with Service Account JSON
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 
          create_credentials_file: true               

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: List GCS buckets
        run: gsutil ls -p "$GCP_PROJECT_ID"